name: Build Gradle project

on:
  push:
    branches:
      - main
    paths:
      - "packages/backend/**"

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: c8n.io
          username: ${{ secrets.DOCKER_USERNAME_PRODUCTS }}
          password: ${{ secrets.DOCKER_PASSWORD_PRODUCTS }}
      - name: Run build with Gradle Wrapper
        run: ./gradlew jib
      - name: 'Deploy'
        uses: 'vimeda/helm@v1.7.0'
        with:
          helm: helm3
          release: 'products'
          namespace: 'products'
          chart: './packages/products/deployment/helm'
          values: |
            commit: ${{ github.sha }}
            databaseUrl: ${{ secrets.DATABASE_URL }}
            databaseUsername: ${{ secrets.DATABASE_USERNAME }}
            databasePassword: ${{ secrets.DATABASE_PASSWORD }}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_PRODUCTS }}'